runn day_number:
    mkdir -p {{day_number}}/bin
    gcc $(find {{day_number}} -type f -name '*.c') -o {{day_number}}/bin/run
    ./{{day_number}}/bin/run

run day_number input_file_path:
    mkdir -p {{day_number}}/bin
    gcc $(find {{day_number}} -type f -name '*.c') -o {{day_number}}/bin/run

    ./{{day_number}}/bin/run ./{{day_number}}/{{input_file_path}}

bun day_number:
    bun {{day_number}}/main.ts

newb day_number:
    mkdir {{day_number}}
    touch ./{{day_number}}/input.txt ./{{day_number}}/main.ts
    echo "import { readInput } from \"../utils\";\n\nconst input = await readInput(\"./{{day_number}}/input.txt\");\n// const input = await readInput(\"./{{day_number}}/test.txt\");\n\nconsole.log(input);" > ./{{day_number}}/main.ts

format:
  find . -name "*.c" -exec clang-format -i {} \;
